In [ ]:
# verificando python's version
!python -V

Python 3.7.13


# 1. *Arrays* no Python

In [ ]:
import numpy as np

In [ ]:
# lendo o arquivo
km = np.loadtxt('carros-km.txt')

In [ ]:
km

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [ ]:
anos = np.loadtxt('carros-anos.txt', dtype=int)

In [ ]:
anos

array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

## Obtendo a média de km por ano

In [ ]:
km_media = km / (2022 - anos)

In [ ]:
km_media

array([2.33736842e+03, 1.84258065e+02, 1.16009375e+03, 0.00000000e+00,
       1.60981250e+03, 1.07280000e+03, 0.00000000e+00, 5.96915385e+03,
       8.26641667e+03, 3.45254545e+03, 6.42950000e+02, 5.36800000e+02,
       4.27490476e+03, 0.00000000e+00, 3.18900000e+03, 1.92678333e+04,
       4.64490000e+03, 0.00000000e+00, 6.18100000e+03, 3.03460000e+03,
       5.05965000e+03, 0.00000000e+00, 3.50282143e+03, 3.32125806e+03,
       0.00000000e+00, 0.00000000e+00, 9.65833333e+02, 0.00000000e+00,
       2.94240000e+03, 3.04454839e+03, 1.20652000e+03, 1.97525926e+03,
       4.43000000e+03, 1.09058065e+03, 1.13355000e+04, 1.62870370e+03,
       0.00000000e+00, 0.00000000e+00, 4.25076923e+02, 0.00000000e+00,
       1.03794444e+04, 2.14536842e+03, 0.00000000e+00, 4.31510000e+03,
       0.00000000e+00, 4.87750000e+02, 3.88583333e+03, 1.14047619e+02,
       0.00000000e+00, 4.22889474e+03, 6.58107692e+03, 3.15600000e+03,
       3.07800000e+03, 5.87168750e+03, 2.94541667e+03, 2.89310714e+03,
      

# 2. Características básicas do Python

## Operações matemáticas

In [ ]:
2+2

4

In [ ]:
3-1

2

In [ ]:
2*3

6

In [ ]:
2 ** 3 # exponencial

8

In [ ]:
10/3

3.3333333333333335

In [ ]:
10//3 # dá o inteiro

3

In [ ]:
10%3 # dá o resto

1

In [ ]:
# segue a sequência padrão - multiplicação e divisão primeiro
5 * 2 + 3 * 2

16

In [ ]:
(5 * 2) + (3 * 2)

16

In [ ]:
5 * (2 + 3) * 2

50

In [ ]:
# _ repete o valor do resultado anterior
_ /2

25.0

In [ ]:
_ - 3 * 2

19.0

## Declaração de variáveis

In [ ]:
ano_atual = 2022
ano_fabricacao = 2013
km_total = 44410.0

In [ ]:
ano_atual

2022

In [ ]:
ano_fabricacao

2013

In [ ]:
km_total

44410.0

$$km_{média} = \frac {km_{total}}{(Ano_{atual} - Ano_{fabricação})}$$

## Operações com variáveis

In [ ]:
ano_atual = 2022
ano_fabricacao = 2013
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)
km_media

4934.444444444444

In [ ]:
km_total_2021 = km_total + km_media

km_total += km_media

In [ ]:
km_total == km_total_2021

True

## Atribuição múltipla

In [ ]:
ano_atual, ano_fabricacao, km_total = 2022, 2013, 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)
km_media

4934.444444444444

## Tipos e mudança de tipo de dados

A aula discutiu os tipos de dados, que podem ser:

 * `int`: números inteiros
 * `float`: números reais
 * `boolean`: boleanos (verdadeiro ou falso)
 * `str`: caracter

Para mudar o tipo de dado de uma variável, posso usar `int()`, `float()` ou `str()`.

In [ ]:
a, b, c, d = 10, 20, "Python é ", "legal"

In [ ]:
a + b

30

In [ ]:
c + d

'Python é legal'

Posso somar variáveis de tipos iguais, mas não de  tipos diferentes, sendo necessário mudar o tipo

In [ ]:
c + str(a)

'Python é 10'

## Exercício

In [ ]:
text = 'A quilometragem média do veículo é '
Km = 100000
Ano_atual = 2019
Ano_fabricacao = 1999

In [ ]:
text + str(int(Km/(Ano_atual - Ano_fabricacao))) + ' km'

'A quilometragem média do veículo é 5000 km'

## Formatando strings

São duas opções para formatar as `strings`. Usando `str.format()` ou `.f` 

In [ ]:
# sem definir variável, só aproveitando a ordem de inserção
print('Olá {}! Este é seu acesso {}'.format('Rodrigo', 32))

Olá Rodrigo! Este é seu acesso 32


In [ ]:
# definindo o nome da variável
print('Olá {nome}! Este é seu acesso {acesso}'.format(nome = 'Rodrigo', acesso = 32))

Olá Rodrigo! Este é seu acesso 32


In [ ]:
# colocando a variável antes
nome = 'Rodrigo'
acesso = 32
print(f'Olá {nome}! Este é seu acesso {acesso}')

Olá Rodrigo! Este é seu acesso 32


# 3. Listas

In [ ]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

## Listas com dados variados

In [ ]:
Carro_1 = ['Jetta Variant', 'Motor 4.0 Turbo', 2003, 44410.0, False, ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 88078.64]
Carro_2 = ['Passat', 'Motor Diesel', 1991, 5712.0, False, ['Central multimídia', 'Teto panorâmico', 'Freios ABS'], 106161.94]

In [ ]:
Carros = [Carro_1, Carro_2]
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

## Operações com listas

### x `in` A

In [ ]:
# x in A
'Rodas de liga' in Acessorios

True

In [ ]:
'Rodas de liga' not in Acessorios

False

### adição

In [ ]:
A = Acessorios[:int(len(Acessorios)/2)]
B = Acessorios[int(len(Acessorios)/2):]

In [ ]:
A + B == Acessorios

True

### tamanho `len`

In [ ]:
len(Acessorios)

8

### Exercício

In [ ]:
carro = [
    'Jetta Variant', 
    'Motor 4.0 Turbo', 
    2003, 
    44410.0, 
    False, 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático'], 
    88078.64
]

In [ ]:
'2003' in carro

False

In [ ]:
'Rodas de liga' in carro

False

In [ ]:
'False' not in carro

True

## Seleções em listas

### Selecionando um item

In [ ]:
Carros

[['Jetta Variant',
  'Motor 4.0 Turbo',
  2003,
  44410.0,
  False,
  ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
  88078.64],
 ['Passat',
  'Motor Diesel',
  1991,
  5712.0,
  False,
  ['Central multimídia', 'Teto panorâmico', 'Freios ABS'],
  106161.94]]

In [ ]:
# primeiro carro
Carros[0]

['Jetta Variant',
 'Motor 4.0 Turbo',
 2003,
 44410.0,
 False,
 ['Rodas de liga', 'Travas elétricas', 'Piloto automático'],
 88078.64]

In [ ]:
# modelo do primeiro carro
Carros[0][0]

'Jetta Variant'

In [ ]:
# lista de acessórios
Carros[0][-2]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

In [ ]:
# Segundo acessório
Carros[0][-2][2]

'Piloto automático'

### Selecionando mais de um item

In [ ]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
Acessorios[2:]

['Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
Acessorios[5:]

['Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']

In [ ]:
Acessorios[-2:]

['Sensor crepuscular', 'Sensor de chuva']

### Exercício 1

In [ ]:
letras = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

Considere também as seguintes seleções na lista letras:

1) ['A', 'B']

2) ['C', 'D', 'E']

3) ['F', 'G', 'H']

In [ ]:
letras[0:2]

['A', 'B']

In [ ]:
letras[2:5]

['C', 'D', 'E']

In [ ]:
letras[-3:]

['F', 'G', 'H']

### Exercício 2

In [ ]:
carros = [
    [
        'Jetta Variant',
        'Motor 4.0 Turbo',
        2003,
        False,
        ['Rodas de liga', 'Travas elétricas', 'Piloto automático']
    ],
    [
        'Passat',
        'Motor Diesel',
        1991,
        True,
        ['Central multimídia', 'Teto panorâmico', 'Freios ABS']
    ]
]

Considere também os seguintes itens:

1) True

2) 'Teto panorâmico'

3) ['Rodas de liga', 'Travas elétricas', 'Piloto automático']

In [ ]:
carros[1][-2]

True

In [ ]:
carros[1][-1][1]

'Teto panorâmico'

In [ ]:
carros[0][-1]

['Rodas de liga', 'Travas elétricas', 'Piloto automático']

## Métodos de listas

In [ ]:
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
Acessorios.sort() # ordena
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [ ]:
Acessorios.append('novo') #adiciona ao final
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas',
 'novo']

In [ ]:
Acessorios.pop() # remove o último
Acessorios

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [ ]:
Acessorios_2 = Acessorios
Acessorios_2

['Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Sensor de estacionamento',
 'Travas elétricas']

In [ ]:
Acessorios_2.append('4 x 4')
print(Acessorios)
print(Acessorios_2)

#  o que acontece com Acessorios_2 também replica com Acessorios

['Ar condicionado', 'Bancos de couro', 'Piloto automático', 'Rodas de liga', 'Sensor crepuscular', 'Sensor de chuva', 'Sensor de estacionamento', 'Travas elétricas', '4 x 4']
['Ar condicionado', 'Bancos de couro', 'Piloto automático', 'Rodas de liga', 'Sensor crepuscular', 'Sensor de chuva', 'Sensor de estacionamento', 'Travas elétricas', '4 x 4']


In [ ]:
Acessorios.pop()
print(Acessorios)
print(Acessorios_2)

['Ar condicionado', 'Bancos de couro', 'Piloto automático', 'Rodas de liga', 'Sensor crepuscular', 'Sensor de chuva', 'Sensor de estacionamento', 'Travas elétricas']
['Ar condicionado', 'Bancos de couro', 'Piloto automático', 'Rodas de liga', 'Sensor crepuscular', 'Sensor de chuva', 'Sensor de estacionamento', 'Travas elétricas']


In [ ]:
Acessorios_2 = Acessorios.copy() # pode ser feito com Acessorios[:] também
Acessorios_2.append('4x4')
print(Acessorios)
print(Acessorios_2)

['Ar condicionado', 'Bancos de couro', 'Piloto automático', 'Rodas de liga', 'Sensor crepuscular', 'Sensor de chuva', 'Sensor de estacionamento', 'Travas elétricas']
['Ar condicionado', 'Bancos de couro', 'Piloto automático', 'Rodas de liga', 'Sensor crepuscular', 'Sensor de chuva', 'Sensor de estacionamento', 'Travas elétricas', '4x4']


### Exercicio 1

In [ ]:
Acessorios = [
    'Rodas de liga', 
    'Travas elétricas', 
    'Piloto automático',
    'Bancos de couro',
    'Ar condicionado'
]

Qual é o código para Out ser:

```
['Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Vidros elétricos']
```

In [ ]:
Acessorios.append('Airbag')
Acessorios.sort()
Acessorios.pop()
Acessorios.append('Vidros eléricos')
Acessorios

['Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Piloto automático',
 'Rodas de liga',
 'Vidros eléricos']

# 4. Condicionais e laços

## Loops com listas

In [ ]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [ ]:
for acessorio in Acessorios:
  print(acessorio)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva


## Usando `range()`

In [ ]:
range(10)

range(0, 10)

In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
for i in range(10):
  print(i ** 2)

0
1
4
9
16
25
36
49
64
81


In [ ]:
quadrado = []

for i in range(10):
  quadrado.append(i ** 2)

quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [ ]:
# é possível fazer o mesmo cálculo em uma linha só - list comprehensions
quadrado = [i ** 2 for i in range(10)]
quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

## Loops aninhados

In [ ]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [ ]:
# juntando todas as listas em uma lista só
Acessorios = []

for lista in dados:
  for item in lista:
    Acessorios.append(item)
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva',
 'Central multimídia',
 'Teto panorâmico',
 'Freios ABS',
 '4 X 4',
 'Painel digital',
 'Piloto automático',
 'Bancos de couro',
 'Câmera de estacionamento',
 'Piloto automático',
 'Controle de estabilidade',
 'Sensor crepuscular',
 'Freios ABS',
 'Câmbio automático',
 'Bancos de couro',
 'Central multimídia',
 'Vidros elétricos']

### Exercício 1

In [ ]:
dados = [ 
    ['A', 'B', 'C'],
    ['D', 'E', 'F'],
    ['G', 'H', 'I']
]

In [ ]:
result = []
for lista in dados:
    for item in lista:
        result.append(item)
result

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

In [ ]:
result_2 = []
for lista in dados:
    result_2 += lista
result_2

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

In [ ]:
[item for lista in dados for item in lista]

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

## Condicionais - `if`

In [ ]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
# selecionando os carros 0 km

zero_km = []

for carro in dados:
  if carro[2]:
    zero_km.append(carro)

zero_km

[['DS5', 2019, True], ['A5', 2019, True]]

In [ ]:
# selecionando carros usados

usados = []

for carro in dados:
  if carro[2] == False: 
    usados.append(carro)

usados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [ ]:
# list comprehension
[carro for carro in dados if carro[2]]

## Condicionais - `if-else`

In [ ]:
zero_km, usados = [], []

for carro in dados:
  if carro[2]:
    zero_km.append(carro)
  else:
    usados.append(carro)

zero_km

[['DS5', 2019, True], ['A5', 2019, True]]

In [ ]:
usados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

## Condicionais - `elif`

In [ ]:
# separando por ano, por exemplo

A, B, C = [], [], []

for carro in dados:
  if carro[1] <= 2000:
    A.append(carro)
  elif carro[1] < 2010:
    B.append(carro)
  else:
    C.append(carro)

A

[['Passat', 1991, False], ['Crossfox', 1990, False]]

In [ ]:
B

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

In [ ]:
C

[['DS5', 2019, True],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

# 5. `Numpy`

In [ ]:
# importando todo o pacote
import numpy
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# importando o pacote e atribuindo um novo nome
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# importando parte do pacote
from numpy import arange
arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Arrays no Numpy

###Criando arrays no Numpy

In [ ]:
import numpy as np

In [ ]:
km = np.array([1000, 2300, 4987, 1500])

In [ ]:
km

array([1000, 2300, 4987, 1500])

In [ ]:
type(km)

numpy.ndarray

In [ ]:
km.dtype

dtype('int64')

### Carregando a partir de um arquivo

In [ ]:
km = np.loadtxt(fname = '/content/drive/MyDrive/Colab Notebooks/Python para Data Science/data/carros-km.txt', dtype = int)

In [ ]:
km.dtype

dtype('int64')

### Arrays com duas dimensões

In [ ]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [ ]:
Acessorios = np.array(dados)

In [ ]:
km.shape

(258,)

In [ ]:
Acessorios.shape

(3, 8)

### Comparando desempenho com listas

O desempenho do `np` é superior ao desempenho com listas, por isso vale mais a pena trabalhar com ele

In [ ]:
np_array = np.arange(1000000)

In [ ]:
py_list = list(range(1000000))

In [ ]:
%time for _ in range(100): np_array *= 2

CPU times: user 75.2 ms, sys: 0 ns, total: 75.2 ms
Wall time: 76.3 ms


In [ ]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

CPU times: user 9.42 s, sys: 2.36 s, total: 11.8 s
Wall time: 11.8 s


## Operações aritméticas com Numpy

### Operações entre arrays e constantes

In [ ]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [ ]:
#idade = 2022 - anos # com lista não funciona

TypeError: ignored

In [ ]:
idade = 2022 - np.array(anos)
idade

array([19, 31, 32,  3, 16])

### Operações entre arrays

In [ ]:
km_media = km / idade
km_media

array([2337.36842105,  184.25806452, 1160.09375   ,    0.        ,
       1609.8125    ])

### Operações com arrays com duas dimensões

In [ ]:
dados = np.array([km, anos])

In [ ]:
dados.shape

(2, 5)

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados[0] == np.array(km)

array([ True,  True,  True,  True,  True])

In [ ]:
dados[1] == np.array(anos)

array([ True,  True,  True,  True,  True])

In [ ]:
km_media = dados[0]/(2022 - dados[1])

### Exercício

O IMC (índice de massa corporal) é um indicador utilizado para detectar situações de obesidade ou desnutrição. Para obter o IMC, basta calcular a razão entre o peso de um indivíduo (kg) e sua altura elevada ao quadrado, conforme mostra a fórmula abaixo:

$IMC = \frac{Peso}{Altura^2}$

Considerando o enunciado acima, verifique cada alternativa e assinale as que calculam corretamente o IMC, não apresentando erro(s) durante o seu cálculo.

In [ ]:
peso = np.array([106.0, 68.5, 75.0])
altura = np.array([1.9, 1.53, 1.75])
IMC = peso / (altura * altura)
IMC

array([29.36288089, 29.26224956, 24.48979592])

In [ ]:
peso = np.array([106.0, 68.5, 75.0])
altura = np.array([1.9, 1.53, 1.75])
IMC = peso / altura ** 2
IMC

array([29.36288089, 29.26224956, 24.48979592])

## Seleções com arrays Numpy

### Indexação

Como na lista, a indexação inicia com o índice 0 e tem mecânica igual.

In [ ]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador[0]

0

In [ ]:
item = 6
index = item - 1
contador[index]

5

In [ ]:
contador[-1]

9

In [ ]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [ ]:
# é possível conseguir um item mesmo com dimensão maior que um
# a estrutura pode ser ndarray[linha][coluna] ou ndarray[linha,coluna]
dados[1,2]

1990.0

### Fatiamentos (slices)

In [ ]:
contador[1:4]

array([1, 2, 3])

In [ ]:
# o passo indica de quanto em quanto eu pulo
contador[1:8:2] # vou do item 2 ao 9 (sem considerar o 9) pulando de 2 em 2

array([1, 3, 5, 7])

In [ ]:
contador[::2] # vou pelo array inteiro (sem restrição), mas de 2 em 2

array([0, 2, 4, 6, 8])

In [ ]:
contador[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados[:, 1:3]

array([[ 5712., 37123.],
       [ 1991.,  1990.]])

In [ ]:
dados[:, 1:3][1]

array([1991., 1990.])

### Indexação com array boleano

In [ ]:
contador = np.arange(10)

In [ ]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [ ]:
contador[contador > 5]

array([6, 7, 8, 9])

In [ ]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [ ]:
dados[1] > 2000

array([ True, False, False,  True,  True])

In [ ]:
dados[: ,dados[1] > 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

### Exercício

In [ ]:
dados = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'solteira', 'feminino'],
        ['Bruno', 'solteiro', 'masculino'],
        ['Rita', 'casada', 'feminino']
    ]
)

Marque a alternativa que mostra o código que permite a seleção, sem utilização de operadores lógicos (`and` e `or`), das informações de **nome** e **estado civil**, **somente das pessoas do sexo masculino**.

In [ ]:
dados[dados[:,2] == "masculino",0:2]

array([['Roberto', 'casado'],
       ['Bruno', 'solteiro']], dtype='<U9')

In [ ]:
dados[::2,:2]

array([['Roberto', 'casado'],
       ['Bruno', 'solteiro']], dtype='<U9')

## Atributos e métodos Numpy

### Atributos

In [ ]:
# ndarray.shape - dimensão do array
dados.shape

(4, 3)

In [ ]:
# ndarray.ndim - número de dimensões do array
dados.ndim

2

In [ ]:
# ndarray.size - número de elementos
dados.size

12

In [ ]:
# ndarray.dtype - tipo dos elementos dentro do array
# lembrando que só se pode ter um tipo dentro do array
dados.dtype

dtype('<U9')

In [ ]:
# ndarray.T - transpoe o array
dados.T

array([['Roberto', 'Sheila', 'Bruno', 'Rita'],
       ['casado', 'solteira', 'solteiro', 'casada'],
       ['masculino', 'feminino', 'masculino', 'feminino']], dtype='<U9')

### Métodos

In [ ]:
# ndarray.tolist() - converte em lista
dados.tolist()

[['Roberto', 'casado', 'masculino'],
 ['Sheila', 'solteira', 'feminino'],
 ['Bruno', 'solteiro', 'masculino'],
 ['Rita', 'casada', 'feminino']]

In [ ]:
# ndarray.reshape(shape[,order]) - order C preenche por linha e F preenche por coluna
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
contador.reshape((5,2), order = 'C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
contador.reshape((5,2), order = 'F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [ ]:
import numpy as np
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [ ]:
np.array(info_carros).reshape((5,2), order = 'F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

In [ ]:
np.array(info_carros).reshape((2,5), order = 'C')

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [ ]:
# ndarray.resize() - 
dados_new = np.array(info_carros).reshape((2,5), order = 'C').copy()
dados_new

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [ ]:
dados_new.resize((3,5), refcheck = False)
dados_new

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006],
       [    0,     0,     0,     0,     0]])

In [ ]:
dados_new[2] = dados_new[0] / (2022 - dados_new[1])
dados_new

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006],
       [ 2337,   184,  1160,     0,  1609]])

## Estatísticas com Numpy

In [1]:
import numpy as np

In [3]:
anos = np.loadtxt("/content/drive/MyDrive/Colab Notebooks/Python para Data Science/data/carros-anos.txt", dtype = int)
km = np.loadtxt("/content/drive/MyDrive/Colab Notebooks/Python para Data Science/data/carros-km.txt")
valor = np.loadtxt("/content/drive/MyDrive/Colab Notebooks/Python para Data Science/data/carros-valor.txt")

In [4]:
anos.shape 

(258,)

In [6]:
# column_stack() faz column bind
dataset = np.column_stack((anos, km, valor))
dataset 
# mesmo a gente indicando que anos seria int, como as outras colunas são float,
# tudo foi convertido para float

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [8]:
# mean - retorna a média para os eixos indicados
np.mean(dataset) # retorna a média de todos os elementos

48489.14648578811

In [10]:
# axis = 0, faz por coluna; axis = 1 faz por linha
np.mean(dataset, axis = 0)

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [11]:
# desvio padrão - std
np.std(dataset, axis = 0)

array([9.70703915e+00, 3.98598270e+04, 2.97541012e+04])

In [13]:
# soma - ndarray.sum
dataset.sum(axis = 0) # também funciona com axis

array([  517938.        , 11480849.        , 25531812.37999999])

In [14]:
# o mesmo funciona com np.sum
np.sum(dataset, axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

## Exercício

In [17]:
idades = np.array([10, 23, 45, 34, 25])

Como obter a média?

In [19]:
np.sum(idades)/idades.size

27.4

In [20]:
np.mean(idades)

27.4

In [23]:
idades.mean()

27.4