In [ ]:
# verificando python's version
!python -V

Python 3.7.13


# 1. *Arrays* no Python

In [ ]:
import numpy as np

In [ ]:
# lendo o arquivo
km = np.loadtxt('carros-km.txt')

In [ ]:
km

array([4.44100e+04, 5.71200e+03, 3.71230e+04, 0.00000e+00, 2.57570e+04,
       1.07280e+04, 0.00000e+00, 7.75990e+04, 9.91970e+04, 3.79780e+04,
       1.28590e+04, 8.05200e+03, 8.97730e+04, 0.00000e+00, 4.14570e+04,
       1.15607e+05, 4.64490e+04, 0.00000e+00, 3.70860e+04, 1.51730e+04,
       1.01193e+05, 0.00000e+00, 9.80790e+04, 1.02959e+05, 0.00000e+00,
       0.00000e+00, 5.79500e+03, 0.00000e+00, 5.88480e+04, 9.43810e+04,
       3.01630e+04, 5.33320e+04, 1.77200e+04, 3.38080e+04, 9.06840e+04,
       4.39750e+04, 0.00000e+00, 0.00000e+00, 5.52600e+03, 0.00000e+00,
       9.34150e+04, 4.07620e+04, 0.00000e+00, 8.63020e+04, 0.00000e+00,
       9.75500e+03, 6.99450e+04, 2.39500e+03, 0.00000e+00, 8.03490e+04,
       8.55540e+04, 5.04960e+04, 6.77160e+04, 9.39470e+04, 3.53450e+04,
       8.10070e+04, 1.19513e+05, 0.00000e+00, 0.00000e+00, 0.00000e+00,
       0.00000e+00, 0.00000e+00, 1.18895e+05, 4.85090e+04, 1.00912e+05,
       9.56490e+04, 0.00000e+00, 9.04950e+04, 0.00000e+00, 2.913

In [ ]:
anos = np.loadtxt('carros-anos.txt', dtype=int)

In [ ]:
anos

array([2003, 1991, 1990, 2019, 2006, 2012, 2019, 2009, 2010, 2011, 2002,
       2007, 2001, 2019, 2009, 2016, 2012, 2019, 2016, 2017, 2002, 2019,
       1994, 1991, 2019, 2019, 2016, 2019, 2002, 1991, 1997, 1995, 2018,
       1991, 2014, 1995, 2019, 2019, 2009, 2019, 2013, 2003, 2019, 2002,
       2019, 2002, 2004, 2001, 2019, 2003, 2009, 2006, 2000, 2006, 2010,
       1994, 2007, 2019, 2019, 2019, 2019, 2019, 2017, 2011, 2001, 1996,
       2019, 1994, 2019, 2007, 1994, 2007, 1997, 2006, 2013, 1994, 2008,
       2008, 2019, 2019, 1999, 2007, 1993, 1995, 2019, 2019, 2016, 2011,
       2019, 2002, 2013, 2017, 2016, 2008, 2018, 2003, 2003, 2004, 2010,
       2019, 2006, 2001, 2019, 2015, 2018, 2017, 1992, 2001, 1993, 1995,
       2003, 2014, 2008, 2013, 2019, 2017, 2019, 2019, 2006, 2015, 2007,
       2005, 2017, 1998, 2019, 1999, 2019, 2009, 2003, 1994, 2019, 1994,
       2019, 2015, 1996, 1997, 1993, 2019, 1992, 1995, 2019, 1990, 2019,
       2019, 1991, 1990, 2012, 2007, 2013, 2000, 20

## Obtendo a média de km por ano

In [ ]:
km_media = km / (2022 - anos)

In [ ]:
km_media

array([2.33736842e+03, 1.84258065e+02, 1.16009375e+03, 0.00000000e+00,
       1.60981250e+03, 1.07280000e+03, 0.00000000e+00, 5.96915385e+03,
       8.26641667e+03, 3.45254545e+03, 6.42950000e+02, 5.36800000e+02,
       4.27490476e+03, 0.00000000e+00, 3.18900000e+03, 1.92678333e+04,
       4.64490000e+03, 0.00000000e+00, 6.18100000e+03, 3.03460000e+03,
       5.05965000e+03, 0.00000000e+00, 3.50282143e+03, 3.32125806e+03,
       0.00000000e+00, 0.00000000e+00, 9.65833333e+02, 0.00000000e+00,
       2.94240000e+03, 3.04454839e+03, 1.20652000e+03, 1.97525926e+03,
       4.43000000e+03, 1.09058065e+03, 1.13355000e+04, 1.62870370e+03,
       0.00000000e+00, 0.00000000e+00, 4.25076923e+02, 0.00000000e+00,
       1.03794444e+04, 2.14536842e+03, 0.00000000e+00, 4.31510000e+03,
       0.00000000e+00, 4.87750000e+02, 3.88583333e+03, 1.14047619e+02,
       0.00000000e+00, 4.22889474e+03, 6.58107692e+03, 3.15600000e+03,
       3.07800000e+03, 5.87168750e+03, 2.94541667e+03, 2.89310714e+03,
      

# 2. Características básicas do Python

## Operações matemáticas

In [ ]:
2+2

4

In [ ]:
3-1

2

In [ ]:
2*3

6

In [ ]:
2 ** 3 # exponencial

8

In [ ]:
10/3

3.3333333333333335

In [ ]:
10//3 # dá o inteiro

3

In [ ]:
10%3 # dá o resto

1

In [ ]:
# segue a sequência padrão - multiplicação e divisão primeiro
5 * 2 + 3 * 2

16

In [ ]:
(5 * 2) + (3 * 2)

16

In [ ]:
5 * (2 + 3) * 2

50

In [ ]:
# _ repete o valor do resultado anterior
_ /2

25.0

In [ ]:
_ - 3 * 2

19.0

## Declaração de variáveis

In [2]:
ano_atual = 2022
ano_fabricacao = 2013
km_total = 44410.0

In [3]:
ano_atual

2022

In [4]:
ano_fabricacao

2013

In [5]:
km_total

44410.0

$$km_{média} = \frac {km_{total}}{(Ano_{atual} - Ano_{fabricação})}$$

## Operações com variáveis

In [11]:
ano_atual = 2022
ano_fabricacao = 2013
km_total = 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)
km_media

4934.444444444444

In [12]:
km_total_2021 = km_total + km_media

km_total += km_media

In [13]:
km_total == km_total_2021

True

## Atribuição múltipla

In [15]:
ano_atual, ano_fabricacao, km_total = 2022, 2013, 44410.0
km_media = km_total / (ano_atual - ano_fabricacao)
km_media

4934.444444444444

# Tipos e mudança de tipo de dados

A aula discutiu os tipos de dados, que podem ser:

 * `int`: números inteiros
 * `float`: números reais
 * `boolean`: boleanos (verdadeiro ou falso)
 * `str`: caracter

Para mudar o tipo de dado de uma variável, posso usar `int()`, `float()` ou `str()`.

In [16]:
a, b, c, d = 10, 20, "Python é ", "legal"

In [17]:
a + b

30

In [18]:
c + d

'Python é legal'

Posso somar variáveis de tipos iguais, mas não de  tipos diferentes, sendo necessário mudar o tipo

In [20]:
c + str(a)

'Python é 10'

## Exercício

In [21]:
text = 'A quilometragem média do veículo é '
Km = 100000
Ano_atual = 2019
Ano_fabricacao = 1999

In [23]:
text + str(int(Km/(Ano_atual - Ano_fabricacao))) + ' km'

'A quilometragem média do veículo é 5000 km'

## Formatando strings

São duas opções para formatar as `strings`. Usando `str.format()` ou `.f` 

In [24]:
# sem definir variável, só aproveitando a ordem de inserção
print('Olá {}! Este é seu acesso {}'.format('Rodrigo', 32))

Olá Rodrigo! Este é seu acesso 32


In [25]:
# definindo o nome da variável
print('Olá {nome}! Este é seu acesso {acesso}'.format(nome = 'Rodrigo', acesso = 32))

Olá Rodrigo! Este é seu acesso 32


In [26]:
# colocando a variável antes
nome = 'Rodrigo'
acesso = 32
print(f'Olá {nome}! Este é seu acesso {acesso}')

Olá Rodrigo! Este é seu acesso 32
